name: Pull Request automatico

on:
  push:
    branches:
        - "**"
    paths:
      - '.github/workflows/**'
      
permissions:
  contents: write
  pull-requests: write


jobs:
    criar-pr-automatico:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v4
          
        - name: Gerar mudança
          run: |
            echo "Atualizado em $(date)" >> log.txt


        - name: Criar pull request
          uses: peter-evans/create-pull-request@v6
          with:
            commit-message: ${{ github.event.head_commit.message }}
            title: ${{ github.event.head_commit.message }}
            body: "PR automático para revisão"
            branch: auto/workflows-update
            base: main
